# Generated by Django 3.0 on 2021-11-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='thumbnail',
            field=models.ImageField(default='true', upload_to=''),
            preserve_default=False,
        ),
    ]
