# Generated by Django 3.0 on 2021-11-07 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_auto_20211107_1552'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
