# Generated by Django 3.2.9 on 2021-11-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0004_alter_applicant_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
