# Generated by Django 3.2.9 on 2021-11-23 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0005_alter_job_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='thumbnail',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
