# Generated by Django 2.2.24 on 2022-01-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0006_auto_20211123_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
