# Generated by Django 2.2.24 on 2022-01-16 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0007_auto_20220116_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='thumbnail',
            new_name='image',
        ),
    ]
