# Generated by Django 2.2.24 on 2022-01-16 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0008_auto_20220116_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='user',
            new_name='User',
        ),
    ]
