# Generated by Django 2.2.24 on 2022-01-16 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0009_auto_20220116_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='User',
            new_name='user',
        ),
    ]
