# Generated by Django 2.2.24 on 2022-01-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0010_auto_20220116_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
