# Generated by Django 2.2.24 on 2022-01-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0012_auto_20220122_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
